# Generated by Django 5.0.2 on 2024-05-08 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
