# Generated by Django 5.0.2 on 2024-05-08 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_comment_post_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
    ]
