# Generated by Django 5.0.2 on 2024-05-10 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_remove_comment_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='comments',
            new_name='comment',
        ),
    ]
