# Generated by Django 5.0.2 on 2024-05-10 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0012_remove_post_comment_comment_post_commented'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post_commented',
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='blogs.post'),
        ),
    ]
