# Generated by Django 5.0.2 on 2024-05-10 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0013_remove_comment_post_commented_comment_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='post_commented',
        ),
    ]
